/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import DAO.DishDAO;
import DAO.ReceiptDAO;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Dish;
import model.Order;
import model.OrderedDish;
import model.Receipt;
import model.Statistic;

/**
 *
 * @author Admin
 */
public class OrderLogFrm extends javax.swing.JDialog {

    /**
     * Creates new form OrderLogFrm
     */
    private List<Receipt> log;
    private Statistic stat;
    public OrderLogFrm(java.awt.Dialog parent, boolean modal, Statistic stat) {
        super(parent, modal);
        this.stat = stat;
        DishDAO dd = new DishDAO();
        this.log = dd.getOrderLog(stat.getStartTime(), stat.getEndTime(), stat.getId());
        initComponents();
    }
//    private void tableDesign(){
//        tblLog.getColumnModel().getColumn(3).setCellRenderer(new MultiLineCellRenderer());
//        
//        tblTable.getColumnModel().getColumn(0).setMinWidth(30); // ID
//        tblTable.getColumnModel().getColumn(0).setMaxWidth(30);
//        tblTable.getColumnModel().getColumn(0).setPreferredWidth(30);
//
//        tblTable.getColumnModel().getColumn(1).setMinWidth(45); // Table
//        tblTable.getColumnModel().getColumn(1).setMaxWidth(45);
//        tblTable.getColumnModel().getColumn(1).setPreferredWidth(45);
//
//        tblTable.getColumnModel().getColumn(2).setMinWidth(40); // Seat quantity
//        tblTable.getColumnModel().getColumn(2).setMaxWidth(40);
//        tblTable.getColumnModel().getColumn(2).setPreferredWidth(40);
//
//        tblTable.getColumnModel().getColumn(3).setMinWidth(100); // Order
//        tblTable.getColumnModel().getColumn(3).setMaxWidth(150);
//        tblTable.getColumnModel().getColumn(3).setPreferredWidth(125);
//
//        tblTable.getColumnModel().getColumn(4).setMinWidth(50); // Checkbox
//        tblTable.getColumnModel().getColumn(4).setMaxWidth(50);
//        tblTable.getColumnModel().getColumn(4).setPreferredWidth(50);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLog = new javax.swing.JTable();
        btnViewReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(stat.getName()+"'s order history");

        tblLog.setModel(loadTableModel());
        jScrollPane1.setViewportView(tblLog);

        btnViewReceipt.setText("View Receipt");
        btnViewReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnViewReceipt)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewReceipt)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReceiptActionPerformed
        // TODO add your handling code here:
        ReceiptDAO rd = new ReceiptDAO();
        Receipt r = getSelectedLog();
        r = rd.getReceiptLog(r);
        ReceiptFrm rf = new ReceiptFrm(r,2);
        rf.setLocationRelativeTo(null);
        rf.setVisible(true);
    }//GEN-LAST:event_btnViewReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public DefaultTableModel loadTableModel(){
        String[] columnNames = { "Order ID","Client Name", "Client ID","Table", "Ordered dish ID", "Order time","quantity" ,"Price","Note","" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0){
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                
                if (columnIndex == 9) return Boolean.class;
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
               
                return column == 9;
            }
        };


        
        for (Receipt i : log) {
            
            
            OrderedDish od = i.getO().getOd().get(0);
            Object[] rowData = { i.getO().getOid(), i.getC().getName(), i.getC().getCid(),i.getO().getT().getPosition(),od.getOdid(), od.getOrderTime(),od.getQuantity(),od.getPrice(), od.getNote(), false};
            model.addRow(rowData);
                
            
        }
        return model;
    }
    public Receipt getSelectedLog(){
        DefaultTableModel model = (DefaultTableModel) tblLog.getModel();
        
        Order o = new Order();
        Receipt r = new Receipt();
        for (int i =0 ; i< model.getRowCount();i++){
            
            Boolean checked = (Boolean) model.getValueAt(i, 9);


            if (Boolean.TRUE.equals(checked)) {
               
                
                o.setOid(Integer.parseInt(model.getValueAt(i,0).toString()));
                r.setO(o);
               
               
                
            }
            
            
        }
        return r;
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderLogFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderLogFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderLogFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderLogFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                OrderLogFrm dialog = new OrderLogFrm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLog;
    // End of variables declaration//GEN-END:variables
}
