/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;
import DAO.DishDAO;
import DAO.TableDAO;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Dish;
import model.Order;
import model.OrderedDish;
import model.Table;
import View.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class PickDishFrm extends javax.swing.JDialog {

    /**
     * Creates new form PickDishFrm
     */
    public static final int ORDER_MODE = 1;
    public static final int UPDATE_MODE = 2;
    private int mode;
    private ReceiptFrm parentFrm;
    private void configureMode() {
        switch (mode) {
            
            case ORDER_MODE:
                
                btnAddDish.setVisible(true);
                btnUpdate.setVisible(false);
                break;
            case UPDATE_MODE:
               
                btnAddDish.setVisible(false);
                btnUpdate.setVisible(true);
                break;
        }
    }
    private Order order;
    public PickDishFrm(java.awt.Frame parent, boolean modal, Order order, int mode) {
        super(parent, modal);
        this.order = order;
        this.mode = mode;
        initComponents();
        configureMode();
        tblDishList.getColumnModel().getColumn(4).setCellRenderer(new MultiLineCellRenderer());
    }
    public PickDishFrm(ReceiptFrm parentFrm, Order order, int mode) {
        
        this.parentFrm = parentFrm;
        this.mode = mode;
        this.order = order;
        initComponents();
        configureMode();
        tblDishList.getColumnModel().getColumn(4).setCellRenderer(new MultiLineCellRenderer());
    }
    public DefaultTableModel loadTableModel() {
        String[] columnNames = { "ID", "Name", "Type", "Price", "Description", "Quantity" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 5) return Integer.class;
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 5; // Chỉ cột số lượng có thể chỉnh sửa
            }
        };

        DishDAO dd = new DishDAO();
        List<Dish> dishList = dd.getDishList();

        List<OrderedDish> orderedDishes = order.getOd() != null ? order.getOd() : new ArrayList<>();

        for (Dish dish : dishList) {
            int quantity = 0;

            // Tìm món ăn này trong danh sách OrderedDish của order
            for (OrderedDish od : orderedDishes) {
                if (od.getD().getId() == dish.getId()) {
                    quantity = od.getQuantity();
                    break;
                }
            }

            Object[] rowData = {
                dish.getId(),
                dish.getName(),
                dish.getType(),
                dish.getPrice(),
                dish.getDes(),
                quantity
            };
            model.addRow(rowData);
        }

        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDishList = new javax.swing.JTable();
        btnAddDish = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDishList.setModel(loadTableModel());
        jScrollPane1.setViewportView(tblDishList);

        btnAddDish.setText("Add Dish");
        btnAddDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDishActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update order");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Dish List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddDish))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDish)
                    .addComponent(btnUpdate))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDishActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblDishList.getModel();
        List<OrderedDish> pickedDish = new ArrayList<>();
        for (int i =0 ; i< model.getRowCount();i++){
            OrderedDish od = new OrderedDish();
            od.setOrderTime(LocalDateTime.now());
            Dish d = new Dish();
            d.setId(Integer.parseInt(model.getValueAt(i, 0).toString()));
            d.setName((String) model.getValueAt(i, 1));
            d.setType((String) model.getValueAt(i, 2));
            d.setPrice(Integer.parseInt(model.getValueAt(i, 3).toString()));
            d.setDes((String) model.getValueAt(i, 4));
            od.setD(d);
            od.setQuantity(Integer.parseInt( model.getValueAt(i, 5).toString()));
            if(Integer.parseInt( model.getValueAt(i, 5).toString())>0){
                pickedDish.add(od);
            }
                
        }
        this.order.setOd(pickedDish);
        this.order.setPaid(false);
        TableDAO td = new TableDAO();
        if (td.uploadOrder(this.order)){
            JOptionPane.showMessageDialog(this, "Order success!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Order failed!");
        }
        
        
    }//GEN-LAST:event_btnAddDishActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblDishList.getModel();
        List<OrderedDish> pickedDish = new ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            OrderedDish od = new OrderedDish();
            od.setOrderTime(LocalDateTime.now());

            Dish d = new Dish();
            d.setId(Integer.parseInt(model.getValueAt(i, 0).toString()));
            d.setName((String) model.getValueAt(i, 1));
            d.setType((String) model.getValueAt(i, 2));

            // ---- Xử lý giá món ăn an toàn ----
            Object priceObj = model.getValueAt(i, 3);
            int price = 0;
            System.out.print(d.getName());
            if (priceObj != null) {
                try {
                    if (priceObj instanceof Integer) {
                        price = (Integer) priceObj;
                    } else {
                        price = Integer.parseInt(priceObj.toString());
                    }
                } catch (NumberFormatException e) {
                    System.err.println("Lỗi chuyển đổi giá món ăn ở dòng " + i + ": " + priceObj);
                }
            }
            d.setPrice(price);
            od.setPrice(price);
            // ----------------------------------

            d.setDes((String) model.getValueAt(i, 4));
            od.setD(d);

            // Xử lý quantity
            int quantity = 0;
            try {
                quantity = Integer.parseInt(model.getValueAt(i, 5).toString());
            } catch (Exception e) {
                System.err.println("Lỗi chuyển đổi số lượng ở dòng " + i + ": " + model.getValueAt(i, 5));
            }
            od.setQuantity(quantity);

            if (quantity > 0) {
                pickedDish.add(od);
            }
        }

        order.setOd(pickedDish);
        order.setPaid(false);
        System.out.println("check");
        for (OrderedDish dish: order.getOd()){
            System.out.println(dish.getPrice());
        }
        parentFrm.loadTableModel(this.order.getOd()); // Cập nhật bảng món ăn
        parentFrm.setData(order); // Cập nhật tổng tiền, thông tin lại
        this.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickDishFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickDishFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickDishFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickDishFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                PickDishFrm dialog = new PickDishFrm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDish;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDishList;
    // End of variables declaration//GEN-END:variables
}
