/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ReceiptDAO;
import DAO.TableDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.*;
import View.*;
import static View.SearchDishFrm.DELETE_MODE;
import static View.SearchDishFrm.EDIT_MODE;
import java.awt.Frame;
import javax.swing.JFrame;


/**
 *
 * @author Admin
 */
public class PickTableFrm extends javax.swing.JFrame {

    /**
     * Creates new form PickTableFrm
     */
    public static final int ORDER_MODE = 1;
    public static final int PAY_MODE = 2;
    private int mode;

    
    private void configureMode() {
        switch (mode) {
            
            case ORDER_MODE:
                
                btnOrder.setVisible(true);
                btnViewReceipt.setVisible(false);
                break;
            case PAY_MODE:
               
                btnOrder.setVisible(false);
                btnViewReceipt.setVisible(true);
                break;
        }
    }
    private User user;
    public PickTableFrm(User user, int mode) {
        
        this.user = user;
        this.mode = mode;
        initComponents();
        
        tableDesign();
        configureMode();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        btnOrder = new javax.swing.JButton();
        btnViewReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Table list");

        tblTable.setModel(loadTableModel());
        jScrollPane1.setViewportView(tblTable);

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnViewReceipt.setText("View Receipt");
        btnViewReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewReceipt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOrder))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrder)
                    .addComponent(btnViewReceipt))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tableDesign(){
        tblTable.getColumnModel().getColumn(3).setCellRenderer(new MultiLineCellRenderer());
        
        tblTable.getColumnModel().getColumn(0).setMinWidth(30); // ID
        tblTable.getColumnModel().getColumn(0).setMaxWidth(30);
        tblTable.getColumnModel().getColumn(0).setPreferredWidth(30);

        tblTable.getColumnModel().getColumn(1).setMinWidth(45); // Table
        tblTable.getColumnModel().getColumn(1).setMaxWidth(45);
        tblTable.getColumnModel().getColumn(1).setPreferredWidth(45);

        tblTable.getColumnModel().getColumn(2).setMinWidth(40); // Seat quantity
        tblTable.getColumnModel().getColumn(2).setMaxWidth(40);
        tblTable.getColumnModel().getColumn(2).setPreferredWidth(40);

        tblTable.getColumnModel().getColumn(3).setMinWidth(100); // Order
        tblTable.getColumnModel().getColumn(3).setMaxWidth(150);
        tblTable.getColumnModel().getColumn(3).setPreferredWidth(125);

        tblTable.getColumnModel().getColumn(4).setMinWidth(50); // Checkbox
        tblTable.getColumnModel().getColumn(4).setMaxWidth(50);
        tblTable.getColumnModel().getColumn(4).setPreferredWidth(50);
    }
    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        PickDishFrm pf = new PickDishFrm(this,true,getSelectedTable(),1);
        pf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            pf.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                tblTable.setModel(loadTableModel());
                tableDesign();
            }
            });
        pf.setVisible(true);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnViewReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReceiptActionPerformed
        // TODO add your handling code here:
        Receipt receipt = new Receipt();
        receipt.setO(getSelectedTable());
        receipt.setU(user);
        ReceiptDAO rd = new ReceiptDAO();
        receipt = rd.getReceiptDetail(receipt);
        ReceiptFrm rf = new ReceiptFrm(receipt,1);
        rf.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                tblTable.setModel(loadTableModel());
                tableDesign();
            }
        });
        rf.setVisible(true);
    }//GEN-LAST:event_btnViewReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public DefaultTableModel loadTableModel(){
        String[] columnNames = {"ID" ,"Table","Seat quantity", "Order","" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0){
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                
                if (columnIndex == 4) return Boolean.class;
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
               
                return column == 4;
            }
        };


        TableDAO td = new TableDAO();
        List<Order> orderList = td.getOrderList();

        for (Order order : orderList) {
            
            
            Object[] rowData = {order.getT().getTid(), order.getT().getPosition(), order.getT().getSeatNumber(),order.orderString(), false};
            model.addRow(rowData);
                
            
        }
        return model;
    }
    public Order getSelectedTable(){
        DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
        Order order = new Order();
        Table table = new Table();
        for (int i =0 ; i< model.getRowCount();i++){
            
            Boolean checked = (Boolean) model.getValueAt(i, 4);


            if (Boolean.TRUE.equals(checked)) {
               table.setTid(Integer.parseInt(model.getValueAt(i,0).toString()));
               table.setPosition(model.getValueAt(i, 1).toString());
               table.setSeatNumber(Integer.parseInt(model.getValueAt(i, 2).toString()));
               
                
            }
            
        }
        order.setT(table);
        return order;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickTableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickTableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickTableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickTableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PickTableFrm().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnViewReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTable;
    // End of variables declaration//GEN-END:variables
}
